trigger:
- main

pool:
  name: cluster-pool

steps:
- checkout: self

# Login to Docker Hub
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub-connection

# Build Docker Image (web-game)
- task: Docker@2
  displayName: Build Docker Image (web-game)
  inputs:
    command: build
    Dockerfile: 2048-game/Dockerfile
    repository: prasanthrajrp/web-game
    tags: |
      latest
      $(Build.BuildId)

# Push Docker Image (web-game)
- task: Docker@2
  displayName: Push Docker Image (web-game)
  inputs:
    command: push
    repository: prasanthrajrp/web-game
    tags: |
      latest
      $(Build.BuildId)
    containerRegistry: dockerhub-connection

# Update image tag inside web-game YAML
- script: |
    sed -i "s|prasanthrajrp/web-game:latest|prasanthrajrp/web-game:$(Build.BuildId)|" k8s/web-game.yaml
  displayName: Update image tag in web-game.yaml

# Apply updated YAML (Deployment + Service)
- script: |
    kubectl apply -f k8s/web-game.yaml -n sample-app
  displayName: Deploy web-game to Kubernetes

# Validate rollout
- script: |
    kubectl -n sample-app rollout status deployment/web-game --timeout=60s
  displayName: Verify web-game rollout
